# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0a8a73b6b9d4c94406a15765dea7c1b7"
name = "Announcement Bar Scheduler"
handle = "announcement-bar-scheduler-3"
application_url = "https://grab-graduated-baking-ways.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://grab-graduated-baking-ways.trycloudflare.com/auth/callback",
  "https://grab-graduated-baking-ways.trycloudflare.com/auth/shopify/callback",
  "https://grab-graduated-baking-ways.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
